// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./ui/views/service-views/404.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    'Home.view': typeof import('./ui/views/home/home.view.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SitePage: typeof import('./ui/components/page/site-page.vue')['default']
  }
}

export {}
