// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Modal: typeof import('./ui/components/modal.vue')['default']
    SitePage: typeof import('./ui/components/page/site-page.vue')['default']
  }
}

export { }
